const REQUEST_SITES = 'sites/REQUEST_SITES';
const RECEIVE_SITES = 'sites/RECEIVE_SITES';
const TOGGLE_CHECKBOX = 'sites/TOGGLE_CHECKBOX';

export {
  REQUEST_SITES,
  RECEIVE_SITES,
  TOGGLE_CHECKBOX,
};
